url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "sraswan.com" # the subpath of your site, e.g. /blog
title: "Shaurya Raswan" # the name of your site, e.g. ACME Corp.
email: sraswan@ucsd.edu
plugins:
  - jekyll-postcss
  - jekyll-feed

postcss:
  cache: false


theme: minima

collections:
  pages:
    output: true

