url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Shaurya Raswan" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-feed

postcss:
  cache: false


theme: minima

collections:
  pages:
    output: true

