name: build-and-deploy
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /sraswan.com/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/sraswan-com/browser
